[package]
name = "rastaplan"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
icalendar = "0.16.10"
chrono = { version = "0.4", features = ["serde"] }
lazy_static = "1.5.0"
